# Environment variables for GitHub Actions
# Copy this file to .env.example and fill in your values

# Vercel Deployment
VERCEL_TOKEN=your_vercel_token_here
VERCEL_ORG_ID=your_vercel_org_id_here
VERCEL_PROJECT_ID=your_vercel_project_id_here

# Docker Hub
DOCKER_USERNAME=your_docker_username_here
DOCKER_PASSWORD=your_docker_password_here

# Production Server
PRODUCTION_HOST=your_production_server_ip
PRODUCTION_USER=your_production_username
PRODUCTION_SSH_KEY=your_production_ssh_private_key

# Security Scanning
SNYK_TOKEN=your_snyk_token_here

# Code Coverage
CODECOV_TOKEN=your_codecov_token_here
